export interface SoftwareItem {
  id: string;
  name: string;
  tagline: string;
  description: string;
  rating: number;
  reviewCount: number;
  price: string;
  priceNote: string;
  category: string;
  features: string[];
  pros: string[];
  logo: string;
  color: string;
  badge?: string;
  platform: string[];
  trialAvailable: boolean;
  url: string;
}

export const softwareData: SoftwareItem[] = [
  {
    id: "monday",
    name: "monday.com",
    tagline: "The Work OS that lets you shape workflows your way",
    description:
      "monday.com is a cloud-based Work OS where teams create workflow apps in minutes to run their processes, projects, and everyday work.",
    rating: 4.6,
    reviewCount: 4892,
    price: "$9",
    priceNote: "per user/month",
    category: "Project Management",
    features: ["Kanban Boards", "Gantt Charts", "Time Tracking", "Automations", "Dashboards", "Integrations"],
    pros: ["Highly customizable", "Easy to use", "Excellent visual interface"],
    logo: "M",
    color: "#FF3D57",
    badge: "Best Overall",
    platform: ["Web", "iOS", "Android"],
    trialAvailable: true,
    url: "#",
  },
  {
    id: "asana",
    name: "Asana",
    tagline: "Work management platform for teams",
    description:
      "Asana helps teams orchestrate their work, from daily tasks to strategic initiatives. Connect all your work in one place and across teams.",
    rating: 4.5,
    reviewCount: 12341,
    price: "$10.99",
    priceNote: "per user/month",
    category: "Task Management",
    features: ["Task Dependencies", "Timeline View", "Portfolios", "Workload", "Goals", "Reporting"],
    pros: ["Clean interface", "Strong integrations", "Good mobile app"],
    logo: "A",
    color: "#F06A6A",
    badge: "Most Popular",
    platform: ["Web", "iOS", "Android"],
    trialAvailable: true,
    url: "#",
  },
  {
    id: "jira",
    name: "Jira",
    tagline: "The #1 software development tool used by agile teams",
    description:
      "Jira is the project management tool for agile teams. Plan, track, release, and report on your software development projects.",
    rating: 4.4,
    reviewCount: 13256,
    price: "$7.75",
    priceNote: "per user/month",
    category: "Agile Development",
    features: ["Scrum Boards", "Backlog", "Roadmaps", "Bug Tracking", "Sprint Planning", "Reports"],
    pros: ["Great for dev teams", "Powerful workflows", "Extensive plugins"],
    logo: "J",
    color: "#0052CC",
    badge: "Best for Dev Teams",
    platform: ["Web", "iOS", "Android"],
    trialAvailable: true,
    url: "#",
  },
  {
    id: "trello",
    name: "Trello",
    tagline: "Collaborate, manage projects, and reach new peaks",
    description:
      "Trello's boards, lists, and cards enable you to organize and prioritize your projects in a fun, flexible, and rewarding way.",
    rating: 4.5,
    reviewCount: 22134,
    price: "$5",
    priceNote: "per user/month",
    category: "Kanban",
    features: ["Kanban Boards", "Power-Ups", "Automations", "Templates", "Calendar View", "Card Covers"],
    pros: ["Very easy to use", "Free tier available", "Visual drag-and-drop"],
    logo: "T",
    color: "#0079BF",
    platform: ["Web", "iOS", "Android"],
    trialAvailable: true,
    url: "#",
  },
  {
    id: "clickup",
    name: "ClickUp",
    tagline: "One app to replace them all",
    description:
      "ClickUp is the world's highest-rated productivity tool. Tasks, Docs, Goals, and Chat all in one place.",
    rating: 4.6,
    reviewCount: 4103,
    price: "$7",
    priceNote: "per user/month",
    category: "All-in-One",
    features: ["Tasks", "Docs", "Goals", "Chat", "Whiteboards", "Dashboards", "Time Tracking"],
    pros: ["Extremely feature-rich", "Highly customizable", "Great value"],
    logo: "C",
    color: "#7B68EE",
    badge: "Best Value",
    platform: ["Web", "iOS", "Android", "Desktop"],
    trialAvailable: true,
    url: "#",
  },
  {
    id: "notion",
    name: "Notion",
    tagline: "Write, plan, share. With AI at your side",
    description:
      "Notion is an all-in-one workspace where you can write, plan, collaborate and get organized. Build your perfect workspace.",
    rating: 4.7,
    reviewCount: 1876,
    price: "$8",
    priceNote: "per user/month",
    category: "Workspace",
    features: ["Databases", "Wikis", "Docs", "Projects", "AI Writing", "Templates"],
    pros: ["Beautiful design", "Very flexible", "AI-powered features"],
    logo: "N",
    color: "#000000",
    badge: "Best for Teams",
    platform: ["Web", "iOS", "Android", "Desktop"],
    trialAvailable: true,
    url: "#",
  },
  {
    id: "wrike",
    name: "Wrike",
    tagline: "Powerful project management for enterprise teams",
    description:
      "Wrike is a collaborative work management platform that brings teams together to accomplish more, no matter the size.",
    rating: 4.2,
    reviewCount: 2387,
    price: "$9.80",
    priceNote: "per user/month",
    category: "Enterprise",
    features: ["Gantt Charts", "Resource Management", "Proofing", "Dashboards", "Time Tracking", "Reports"],
    pros: ["Enterprise-grade security", "Advanced reporting", "Custom workflows"],
    logo: "W",
    color: "#00A99D",
    platform: ["Web", "iOS", "Android"],
    trialAvailable: true,
    url: "#",
  },
  {
    id: "smartsheet",
    name: "Smartsheet",
    tagline: "The enterprise platform for modern work management",
    description:
      "Smartsheet is a cloud-based platform that enables teams to plan, capture, manage, automate, and report on work at scale.",
    rating: 4.4,
    reviewCount: 3012,
    price: "$9",
    priceNote: "per user/month",
    category: "Spreadsheet-Based",
    features: ["Grid View", "Gantt Charts", "Automations", "Dashboards", "Forms", "Resource Management"],
    pros: ["Familiar spreadsheet feel", "Strong automations", "Good for enterprises"],
    logo: "S",
    color: "#0073E6",
    platform: ["Web", "iOS", "Android"],
    trialAvailable: true,
    url: "#",
  },
  {
    id: "basecamp",
    name: "Basecamp",
    tagline: "All your projects, teams, and company communication together",
    description:
      "Basecamp is the project management platform that brings people together, no matter where they work.",
    rating: 4.3,
    reviewCount: 14563,
    price: "$15",
    priceNote: "per user/month",
    category: "Team Collaboration",
    features: ["To-do Lists", "Message Boards", "Campfire Chat", "Schedules", "File Storage", "Check-ins"],
    pros: ["Simple and clean", "Flat pricing option", "Great for remote teams"],
    logo: "B",
    color: "#00B34D",
    platform: ["Web", "iOS", "Android"],
    trialAvailable: true,
    url: "#",
  },
  {
    id: "linear",
    name: "Linear",
    tagline: "The issue tracking tool you'll enjoy using",
    description:
      "Linear streamlines software projects, sprints, tasks, and bug tracking. Purpose-built for software development teams.",
    rating: 4.8,
    reviewCount: 521,
    price: "$8",
    priceNote: "per user/month",
    category: "Issue Tracking",
    features: ["Issue Tracking", "Cycles (Sprints)", "Roadmaps", "Git Integration", "Triage", "Insights"],
    pros: ["Lightning fast", "Beautiful design", "Keyboard-first"],
    logo: "L",
    color: "#5E6AD2",
    badge: "Rising Star",
    platform: ["Web", "iOS", "Desktop"],
    trialAvailable: true,
    url: "#",
  },
  {
    id: "airtable",
    name: "Airtable",
    tagline: "Build the future with flexible data",
    description:
      "Airtable is a low-code platform for building collaborative apps. Customize your workflow, collaborate, and achieve ambitious outcomes.",
    rating: 4.6,
    reviewCount: 1943,
    price: "$10",
    priceNote: "per user/month",
    category: "Database-Driven",
    features: ["Grid", "Gallery", "Kanban", "Calendar", "Gantt", "Automations", "Interfaces"],
    pros: ["Super flexible", "Multiple view types", "Strong API"],
    logo: "Ai",
    color: "#FCB400",
    platform: ["Web", "iOS", "Android"],
    trialAvailable: true,
    url: "#",
  },
  {
    id: "teamwork",
    name: "Teamwork",
    tagline: "Project management software for client-focused teams",
    description:
      "Teamwork is designed for teams who bill for time and want to keep clients happy with accurate project delivery.",
    rating: 4.4,
    reviewCount: 789,
    price: "$9.99",
    priceNote: "per user/month",
    category: "Client Projects",
    features: ["Time Tracking", "Billing", "Client Portals", "Milestones", "Gantt Charts", "Proofs"],
    pros: ["Great for agencies", "Client billing features", "Detailed time reports"],
    logo: "Tw",
    color: "#31A8FF",
    platform: ["Web", "iOS", "Android"],
    trialAvailable: true,
    url: "#",
  },
  {
    id: "zoho-projects",
    name: "Zoho Projects",
    tagline: "Plan, track, and collaborate with your team",
    description:
      "Zoho Projects is online project management software for planning, tracking, and collaborating with your team on projects.",
    rating: 4.3,
    reviewCount: 6234,
    price: "$5",
    priceNote: "per user/month",
    category: "Project Management",
    features: ["Tasks", "Milestones", "Gantt Charts", "Time Tracking", "Bug Tracking", "Forums"],
    pros: ["Affordable pricing", "Good Zoho integration", "Easy to set up"],
    logo: "Z",
    color: "#E74C3C",
    platform: ["Web", "iOS", "Android"],
    trialAvailable: true,
    url: "#",
  },
  {
    id: "ms-project",
    name: "Microsoft Project",
    tagline: "Empower teams with project and portfolio management tools",
    description:
      "Microsoft Project helps you plan, manage, and deliver projects with powerful task management and scheduling tools.",
    rating: 4.1,
    reviewCount: 1678,
    price: "$10",
    priceNote: "per user/month",
    category: "Enterprise",
    features: ["Gantt Charts", "Resource Management", "Roadmaps", "Timelines", "Reporting", "Portfolios"],
    pros: ["Microsoft ecosystem integration", "Powerful scheduling", "Enterprise features"],
    logo: "MP",
    color: "#217346",
    platform: ["Web", "Desktop"],
    trialAvailable: true,
    url: "#",
  },
  {
    id: "hive",
    name: "Hive",
    tagline: "The world's first democratically built productivity platform",
    description:
      "Hive is the project management platform built for teams. Manage tasks, communicate, and get things done in one place.",
    rating: 4.5,
    reviewCount: 492,
    price: "$12",
    priceNote: "per user/month",
    category: "All-in-One",
    features: ["Action Cards", "Gantt Charts", "Kanban", "Time Tracking", "Forms", "AI Features"],
    pros: ["Action-focused workflow", "Good analytics", "Flexible views"],
    logo: "H",
    color: "#FF8C00",
    platform: ["Web", "iOS", "Android"],
    trialAvailable: true,
    url: "#",
  },
  {
    id: "proofhub",
    name: "ProofHub",
    tagline: "Project management and team collaboration tool",
    description:
      "ProofHub is an all-in-one project management software that helps you plan, organize, and deliver projects on time.",
    rating: 4.4,
    reviewCount: 88,
    price: "$45",
    priceNote: "flat/month (unlimited users)",
    category: "All-in-One",
    features: ["Tasks", "Discussions", "Proofing", "Gantt Charts", "Time Tracking", "Reports"],
    pros: ["Flat pricing model", "Unlimited users", "Built-in proofing"],
    logo: "PH",
    color: "#F7367B",
    platform: ["Web", "iOS", "Android"],
    trialAvailable: true,
    url: "#",
  },
  {
    id: "nifty",
    name: "Nifty",
    tagline: "The all-in-one project management tool",
    description:
      "Nifty is a project management tool that helps teams streamline communication, planning, and milestone tracking.",
    rating: 4.7,
    reviewCount: 434,
    price: "$8",
    priceNote: "per user/month",
    category: "Milestone-Driven",
    features: ["Milestones (Roadmaps)", "Tasks", "Docs", "Chat", "Time Tracking", "Portfolios"],
    pros: ["Great for goal tracking", "Milestone roadmaps", "Clean UI"],
    logo: "Ni",
    color: "#4BD7D6",
    badge: "Rising Star",
    platform: ["Web", "iOS", "Android"],
    trialAvailable: true,
    url: "#",
  },
  {
    id: "teamgantt",
    name: "TeamGantt",
    tagline: "The painless way to plan and manage projects",
    description:
      "TeamGantt is simple, collaborative gantt chart software for project management that your whole team will love.",
    rating: 4.5,
    reviewCount: 637,
    price: "$19",
    priceNote: "per user/month",
    category: "Gantt Charts",
    features: ["Gantt Charts", "Task Dependencies", "Resource Management", "Time Tracking", "Portfolios"],
    pros: ["Best-in-class Gantt charts", "Easy to learn", "Great for planning"],
    logo: "TG",
    color: "#34495E",
    platform: ["Web", "iOS", "Android"],
    trialAvailable: true,
    url: "#",
  },
  {
    id: "paymo",
    name: "Paymo",
    tagline: "Work management for small business & freelancers",
    description:
      "Paymo is a work management app for small teams that need to manage projects, track time, and send invoices.",
    rating: 4.7,
    reviewCount: 534,
    price: "$9.95",
    priceNote: "per user/month",
    category: "Freelancer",
    features: ["Task Management", "Time Tracking", "Invoicing", "Gantt Charts", "Kanban", "Reports"],
    pros: ["Great for freelancers", "Built-in invoicing", "Time-to-invoice workflow"],
    logo: "Py",
    color: "#E91E8C",
    platform: ["Web", "iOS", "Android"],
    trialAvailable: true,
    url: "#",
  },
  {
    id: "scoro",
    name: "Scoro",
    tagline: "Business management software for professional services",
    description:
      "Scoro is an end-to-end business management platform that allows professional services companies to run their entire business.",
    rating: 4.5,
    reviewCount: 371,
    price: "$22",
    priceNote: "per user/month",
    category: "Business Management",
    features: ["Projects", "Tasks", "CRM", "Quoting", "Billing", "Reporting", "Dashboards"],
    pros: ["Comprehensive tool", "Great for agencies", "CRM + PM in one"],
    logo: "Sc",
    color: "#1ABC9C",
    platform: ["Web", "iOS", "Android"],
    trialAvailable: true,
    url: "#",
  },
  {
    id: "liquidplanner",
    name: "LiquidPlanner",
    tagline: "Predictive project management for teams",
    description:
      "LiquidPlanner uses predictive scheduling to automatically account for uncertainty and give teams realistic timelines.",
    rating: 4.2,
    reviewCount: 643,
    price: "$15",
    priceNote: "per user/month",
    category: "Predictive Scheduling",
    features: ["Predictive Scheduling", "Resource Management", "Risk Analysis", "Time Tracking", "Portfolios"],
    pros: ["Handles uncertainty well", "Realistic forecasts", "Good resource planning"],
    logo: "LP",
    color: "#2980B9",
    platform: ["Web", "iOS", "Android"],
    trialAvailable: true,
    url: "#",
  },
  {
    id: "activecollab",
    name: "ActiveCollab",
    tagline: "The project management tool that grows with your business",
    description:
      "ActiveCollab is a self-hosted or cloud project management tool with tasks, time tracking, and invoicing.",
    rating: 4.5,
    reviewCount: 397,
    price: "$7.50",
    priceNote: "per user/month",
    category: "Self-Hosted Option",
    features: ["Tasks", "Time Tracking", "Invoicing", "Kanban", "Gantt", "Team Chat"],
    pros: ["Self-hosting available", "All-in-one solution", "Affordable"],
    logo: "AC",
    color: "#FF5A5A",
    platform: ["Web", "iOS", "Android"],
    trialAvailable: true,
    url: "#",
  },
  {
    id: "workzone",
    name: "Workzone",
    tagline: "Project management software for marketing teams",
    description:
      "Workzone is project management and collaboration software ideal for marketing, creative, and operations teams.",
    rating: 4.5,
    reviewCount: 189,
    price: "$24",
    priceNote: "per user/month",
    category: "Marketing Teams",
    features: ["Task Management", "Dependencies", "Gantt Charts", "Workload", "Custom Reports", "Branding"],
    pros: ["Great for marketing", "Strong reporting", "Client-friendly"],
    logo: "Wz",
    color: "#8E44AD",
    platform: ["Web"],
    trialAvailable: false,
    url: "#",
  },
  {
    id: "planview",
    name: "Planview",
    tagline: "Enterprise portfolio & project management",
    description:
      "Planview is the global leader in connected work, delivering the most complete, flexible portfolio and project management platform.",
    rating: 4.1,
    reviewCount: 423,
    price: "Custom",
    priceNote: "contact for pricing",
    category: "Enterprise Portfolio",
    features: ["Portfolio Management", "Resource Management", "Strategic Planning", "OKRs", "Roadmaps"],
    pros: ["Enterprise-grade", "Portfolio visibility", "Strategic alignment"],
    logo: "Pv",
    color: "#0070C0",
    platform: ["Web"],
    trialAvailable: false,
    url: "#",
  },
  {
    id: "podio",
    name: "Podio",
    tagline: "Custom collaboration and project management platform",
    description:
      "Podio is a flexible, customizable platform for team communication and project management. Build your own apps inside Podio.",
    rating: 4.2,
    reviewCount: 441,
    price: "$9.00",
    priceNote: "per user/month",
    category: "Custom Apps",
    features: ["Custom App Builder", "Tasks", "Workspaces", "Automated Workflows", "File Sharing", "CRM"],
    pros: ["Highly customizable", "Build your own apps", "Citrix-backed"],
    logo: "Po",
    color: "#00ADEF",
    platform: ["Web", "iOS", "Android"],
    trialAvailable: true,
    url: "#",
  },
];

export const categories = [
  "All",
  "Project Management",
  "Agile Development",
  "Kanban",
  "Gantt Charts",
  "All-in-One",
  "Enterprise",
  "Team Collaboration",
  "Issue Tracking",
];
